---
title: "task4"
author: "Ning Hu"
date: "10/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
#library(reticulate)
#use_condaenv('r-reticulate',required = TRUE)
```

```{r,eval=FALSE}
py_install('matplotlib')
py_install('seaborn')
py_install('pandas')
py_install('numpy')
```


```{python,eval=FALSE}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
```

```{python,eval=FALSE}
transactions = pd.read_csv("data/transactions.csv")
transactions['account_id'].value_counts().sort_values(ascending=False)
```


```{python,eval=FALSE}
transactions = transactions.loc[transactions['account_id'] == 8261]
transactions['date'] = pd.to_datetime(transactions['date'])
transactions = transactions.set_index('date').sort_index()
```


```{python,eval=FALSE}
plt.figure(1)
fig1 = sns.lineplot(x=transactions.index, y=transactions['amount'], data=transactions, hue=transactions['type'])
fig1.set_title('8261\'s debit & credit transactions amounts over time')
plt.show()
```

```{python,eval=FALSE}
plt.figure(2)
fig2 = sns.lineplot(x=transactions.index, y=transactions['amount'], data=transactions, hue=transactions['method'])
fig2.set_title('8261\'s transactions amounts of different methods over time')
plt.show()
```



```{python,eval=FALSE}
plt.figure(3)
fig3 = sns.lineplot(x=transactions.index, y=transactions['amount'], data=transactions, hue=transactions['category'])
fig3.set_title('8261\'s transactions amounts of different categories over time')
plt.show()
```



```{r,include=FALSE}
library(tidyverse)
```

```{r,include=FALSE}
trans <- read_csv('data/transactions.csv')
accts <- read_csv('data/accounts_analytical.csv')
```

```{r,include=FALSE}
## look for the account_id with the highest number of transactions
ID <- trans %>%
  group_by(account_id) %>%
  summarise(num_transactions = n()) %>%
  top_n(n=1)
ID

```

```{r,include=FALSE}
trans4 <- trans %>%
  filter(account_id==ID[[1]]) %>%
  arrange(date)
```


```{r,echo=FALSE}
trans4 %>% 
  ggplot(aes(x = date,y = amount, color=type))+
  geom_line()+
  labs(title = '8261\'s debit & credit transactions amounts over time')

```
```{r,echo=FALSE}
trans4 %>% 
  ggplot(aes(x = date,y = amount, color=method))+
  geom_line()+
  labs(title = '8261\'s transactions amounts of different methods over time')

```

```{r,echo=FALSE}
trans4 %>% drop_na(category) %>%
  ggplot(aes(x = date,y = amount, color=category))+
  geom_line()+
  labs(title = '8261\'s transactions amounts of different category over time')
```
